### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by Eloitor** [Luukdegram/juicebox#2]
I tried to run `zig build` in the folder, but I get this error:
```
./src/Manager.zig:16:1: error: invalid token: 'ContainerDocComment'
//! The `Manager` is the heart of Juicebox. It manages all window creation,
^
```

If I turn all `//!` into `//` I get this other error.
```
./protocol.zig:173:48: error: container 'std.builtin' has no member called 'endian'
    byte_order: u8 = if (@import("std").builtin.endian == .Big) 0x42 else 0x6c,
```

My version of zig is 0.8.0.

**Comment by Luukdegram** [comment]
Hi!

It's been a while since I've had the mood and time to work on this. It hadn't been updated for a while and it has quite some compile errors now. I've just now updated it to the latest **master** of zig. So you should be able to run it locally using 
`zig build xephyr -Dsize=1200x800 -Dconfig_path=config` (You must be in the root folder of the project and have xephyr installed).

edit: This means it requires the latest version of Zig, as I do not use 0.8.0 myself.
